# Generated by Django 4.2.2 on 2023-06-19 13:03

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("email_address", models.EmailField(max_length=150)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="KZ"
                    ),
                ),
                ("message", models.CharField(max_length=2000)),
                ("date_time", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
